version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:14
    ports:
      - ${PGPORT}:${PGPORT}
    networks:
      - nw
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGPORT=${PGPORT}

  parser:
    container_name: parser
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - nw
    volumes:
      - ./log/:/log/
      - ./config.json:/config.json:ro

networks:
  nw:
